language: python

matrix:
  include:
  - python: 3.5
    dist: trusty
    sudo: false
  - python: 3.6
    dist: trusty
    sudo: false
  - python: 3.7
    dist: xenial
    sudo: true

install:
  - python setup.py install
  - pip install coveralls

script:
  - python test.py
