language: python
matrix:
  include:
  - python: 3.5
    dist: trusty
    sudo: false
  - python: 3.6
    dist: trusty
    sudo: false
  - python: 3.7
    dist: xenial
    sudo: true
install:
- python setup.py install
script:
- python test.py

deploy:
  provider: releases
  api_key: $token
  file:
  - "dist/jejunuMeals-*-py3-none-any.whl"
  - "jejunuMeals.egg-info"
  - "build/bdist.macosx-*-x86_64"
  on:
    tags: true

deploy:
  provider: pypi
  user: BetaFish
  password: $pw
  on:
    tags: true
    branch: master
